/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes the query messages available in the contract.
 */
export type QueryMsg =
  | {
      config: {};
    }
  | {
      active_props: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      finished_props: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      prop_detail: {
        proposal_id: number;
        user?: string | null;
      };
    }
  | {
      prop_voters: {
        limit?: number | null;
        proposal_id: number;
        start_after?: [number, string] | null;
      };
    };
