/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      mint: {
        recipient: string;
        token_id: string;
      };
    }
  | {
      update_token_data: TokenMetadata[];
    }
  | {
      update_config: {
        add_minters?: string[] | null;
        paused?: boolean | null;
        remove_minters?: string[] | null;
      };
    }
  | {
      update_config_admin: {
        controller?: string | null;
      };
    };

export interface TokenMetadata {
  metadata?: NftMetadataStandard | null;
  token_id: string;
}
export interface NftMetadataStandard {
  animation_url?: string | null;
  attributes?: NftTraitStandard[] | null;
  background_color?: string | null;
  description?: string | null;
  external_url?: string | null;
  image?: string | null;
  image_data?: string | null;
  name?: string | null;
  youtube_url?: string | null;
  [k: string]: unknown;
}
export interface NftTraitStandard {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
