/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  collection_addr: string;
  controller?: string | null;
  global_config_addr: string;
  minters?: string[] | null;
}
