/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This enum describes voters status.
 */
export type BlacklistedVotersResponse =
  | {
      voters_blacklisted: {};
    }
  | {
      voters_not_blacklisted: {
        voter: string;
      };
    };
