/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  nft_instantiate: InstantiateMsg1;
  owner: string;
}
export interface InstantiateMsg1 {
  /**
   * The minter is the only one who can create new NFTs. This is designed for a base NFT that is controlled by an external program or contract. You will likely replace this with custom logic in custom NFTs
   */
  minter: string;
  /**
   * Name of the NFT contract
   */
  name: string;
  /**
   * Symbol of the NFT contract
   */
  symbol: string;
}
