/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LsdTypeFor_Addr =
  | {
      eris: {
        addr: Addr;
        denom: string;
      };
    }
  | {
      backbone: {
        addr: Addr;
        denom: string;
      };
    };
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;
export type UtilizationMethod = {
  steps: [Decimal, Decimal][];
};
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;

/**
 * This struct is used to return a query result with the general contract configuration.
 */
export interface ConfigResponse {
  config: Description;
  fee_config: FeeConfigFor_Addr;
  lp_token: LpToken;
  owner: Addr;
  whitelist?: Addr[] | null;
}
/**
 * This structure stores the main config parameters for a constant product pair contract.
 */
export interface Description {
  lsds: LsdConfigFor_Addr[];
  unbond_time_s: number;
  utilization_method: UtilizationMethod;
  utoken: string;
}
export interface LsdConfigFor_Addr {
  disabled: boolean;
  lsd_type: LsdTypeFor_Addr;
  name: string;
}
export interface FeeConfigFor_Addr {
  immediate_withdraw_fee: Decimal;
  protocol_fee_contract: Addr;
  protocol_performance_fee: Decimal;
  protocol_withdraw_fee: Decimal;
}
export interface LpToken {
  denom: string;
  total_supply: Uint128;
}
