/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes the query messages available in the contract.
 */
export type QueryMsg =
  | {
      config: {};
    }
  | {
      state: {
        details?: boolean | null;
      };
    }
  | {
      user_info: {
        address: string;
      };
    }
  | {
      takeable: {
        wanted_profit?: Decimal | null;
      };
    }
  | {
      unbond_requests: {
        address: string;
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      exchange_rates: {
        limit?: number | null;
        start_after_d?: number | null;
      };
    };
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
