/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {};
    }
  | {
      state: {};
    }
  | {
      user_info: {
        user: string;
      };
    }
  | {
      executions: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      execution: {
        id: number;
      };
    };
