/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {};
    }
  | {
      get_offers: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      get_offer: {
        offer_id: number;
      };
    }
  | {
      get_user_offers: {
        limit?: number | null;
        start_after?: [string, number] | null;
        user: string;
      };
    }
  | {
      get_user_offers_for_collection: {
        collection: string;
        limit?: number | null;
        start_after?: number | null;
        user: string;
      };
    };
