/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;

export interface IcaResponse {
  /**
   * Balances of all host ICQ accounts
   */
  account_balances: AccountBalances;
  ica_config: IcaConfig;
  ica_senders: IcaSender[];
  [k: string]: unknown;
}
export interface AccountBalances {
  accounts: {
    [k: string]: AccountBalance;
  };
}
export interface AccountBalance {
  coins: Coins;
}
export interface Coins {
  /**
   * @minItems 2
   * @maxItems 2
   */
  [k: string]: [Uint128, number];
}
export interface IcaConfig {
  connection_id: string;
  controller_channel: string;
  host_channel: string;
  host_prefix: string;
  min_fee_withdrawal?: Uint128 | null;
  min_reward_restake?: Uint128 | null;
  version: string;
}
export interface IcaSender {
  account_id: string;
  address: string;
  controller_connection_id: string;
}
