/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
export type DelegationStrategyFor_String =
  | {
      defined: {
        shares_bps: [string, BasicPoints][];
        [k: string]: unknown;
      };
    }
  | {
      gauges: {
        /**
         * gauges based on vAmp voting
         */
        amp_gauges: string;
        /**
         * max amount of delegation needed
         */
        max_delegation_bps: BasicPoints;
        /**
         * min amount of delegation needed
         */
        min_delegation_bps: BasicPoints;
        /**
         * count of validators that should receive delegations
         */
        validator_count: number;
        [k: string]: unknown;
      };
    };
/**
 * BasicPoints struct implementation. BasicPoints value is within [0, 10000] interval. Technically BasicPoints is wrapper over [`u16`] with additional limit checks and several implementations of math functions so BasicPoints object can be used in formulas along with [`Uint128`] and [`Decimal`].
 */
export type BasicPoints = number;

export interface InstantiateMsg {
  /**
   * Account who can call TuneAndRedelegate
   */
  delegation_operator: string;
  /**
   * Name of the liquid staking token
   */
  denom: string;
  /**
   * How often the unbonding queue is to be executed, in seconds
   */
  epoch_period: number;
  /**
   * Contract address where fees are sent
   */
  fee_addr: string;
  /**
   * Account who can call harvest
   */
  operator: string;
  /**
   * Account who can call certain privileged functions
   */
  owner: string;
  /**
   * Fees that are being applied during reinvest of staking rewards
   */
  reward_fee: Decimal;
  /**
   * Strategy how delegations should be handled
   */
  strategy?: DelegationStrategyFor_String | null;
  /**
   * The staking module's unbonding time, in seconds
   */
  unbond_period: number;
  /**
   * Denom of the underlaying staking token
   */
  utoken_controller: string;
  /**
   * Denom of the underlaying staking token
   */
  utoken_host: string;
  /**
   * Initial set of validators who will receive the delegations
   */
  validators: string[];
  [k: string]: unknown;
}
