/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      ica: {
        [k: string]: unknown;
      };
    }
  | {
      state: {
        [k: string]: unknown;
      };
    }
  | {
      simulate_wanted_delegations: {
        /**
         * by default uses the next period to look into the future.
         */
        period?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      pending_batch: {
        [k: string]: unknown;
      };
    }
  | {
      previous_batch: number;
    }
  | {
      previous_batches: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond_requests_by_batch: {
        id: number;
        limit?: number | null;
        start_after?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond_requests_by_user_details: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
        [k: string]: unknown;
      };
    }
  | {
      exchange_rates: {
        limit?: number | null;
        start_after?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      virtual_delegations: {
        [k: string]: unknown;
      };
    };
