/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      bond: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      donate: {
        [k: string]: unknown;
      };
    }
  | {
      withdraw_unbonded: {
        receiver: string;
        [k: string]: unknown;
      };
    }
  | {
      queue_unbond: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      submit_batch: {
        [k: string]: unknown;
      };
    }
  | {
      accept_ownership: {
        [k: string]: unknown;
      };
    }
  | {
      tune_and_redelegate: {
        [k: string]: unknown;
      };
    }
  | {
      o_withdraw_rewards: {
        validators?: string[] | null;
        [k: string]: unknown;
      };
    }
  | {
      vote: {
        proposal_id: number;
        votes: [Decimal, VoteOption][];
        [k: string]: unknown;
      };
    }
  | {
      a_add_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      a_remove_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      a_transfer_ownership: {
        new_owner: string;
        [k: string]: unknown;
      };
    }
  | {
      a_drop_ownership_proposal: {
        [k: string]: unknown;
      };
    }
  | {
      a_tune_delegations: {
        [k: string]: unknown;
      };
    }
  | {
      a_rebalance: {
        min_redelegation?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      a_create_accounts: {
        connection_id: string;
        controller_channel: string;
        host_channel: string;
        host_prefix: string;
        min_fee_withdrawal?: Uint128 | null;
        min_reward_restake?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      a_register_icqs: {
        balance_blocks?: number | null;
        delegations_blocks?: number | null;
        denoms: string[];
        [k: string]: unknown;
      };
    }
  | {
      a_update_config: {
        ack_fee?: Coin[] | null;
        /**
         * Sets the stages preset Specifies wether donations are allowed.
         */
        allow_donation?: boolean | null;
        /**
         * Update the delegation_operator
         */
        delegation_operator?: string | null;
        /**
         * Contract address where fees are sent
         */
        fee_addr?: string | null;
        min_fee_withdrawal?: Uint128 | null;
        min_reward_restake?: Uint128 | null;
        /**
         * Sets a new operator
         */
        operator?: string | null;
        /**
         * Fees that are being applied during reinvest of staking rewards
         */
        reward_fee?: Decimal | null;
        /**
         * Strategy how delegations should be handled
         */
        strategy?: DelegationStrategyFor_String | null;
        timeout_fee?: Coin[] | null;
        /**
         * Update the vote_operator
         */
        voter?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      r_submit_batch: {
        [k: string]: unknown;
      };
    }
  | {
      r_withdraw_unbonded_for_user: {
        user: Addr;
        [k: string]: unknown;
      };
    }
  | {
      callback: CallbackMsg;
    };
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
export type DelegationStrategyFor_String =
  | {
      defined: {
        shares_bps: [string, BasicPoints][];
        [k: string]: unknown;
      };
    }
  | {
      gauges: {
        /**
         * gauges based on vAmp voting
         */
        amp_gauges: string;
        /**
         * max amount of delegation needed
         */
        max_delegation_bps: BasicPoints;
        /**
         * min amount of delegation needed
         */
        min_delegation_bps: BasicPoints;
        /**
         * count of validators that should receive delegations
         */
        validator_count: number;
        [k: string]: unknown;
      };
    };
/**
 * BasicPoints struct implementation. BasicPoints value is within [0, 10000] interval. Technically BasicPoints is wrapper over [`u16`] with additional limit checks and several implementations of math functions so BasicPoints object can be used in formulas along with [`Uint128`] and [`Decimal`].
 */
export type BasicPoints = number;
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;
export type CallbackMsg =
  | {
      rewards_to_hub: {
        amount: Uint128;
      };
    }
  | {
      fees_to_collector: {
        amount: Uint128;
      };
    }
  | {
      stake_on_host: {};
    }
  | {
      send_to_host: {};
    };

export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
