/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NftInfoResponseFor_Nullable_NftMetadataStandard {
  /**
   * You can add any custom metadata here when you extend cw721-base
   */
  extension?: NftMetadataStandard | null;
  /**
   * Universal resource identifier for this NFT Should point to a JSON file that conforms to the ERC721 Metadata JSON Schema
   */
  token_uri?: string | null;
}
export interface NftMetadataStandard {
  animation_url?: string | null;
  attributes?: NftTraitStandard[] | null;
  background_color?: string | null;
  description?: string | null;
  external_url?: string | null;
  image?: string | null;
  image_data?: string | null;
  name?: string | null;
  youtube_url?: string | null;
  [k: string]: unknown;
}
export interface NftTraitStandard {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
