/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes the query messages available in the contract.
 */
export type QueryMsg =
  | {
      tune_info: {};
    }
  | {
      config: {};
    }
  | {
      validator_info: {
        validator_addr: string;
      };
    }
  | {
      validator_info_at_period: {
        period: number;
        validator_addr: string;
      };
    }
  | {
      validator_infos: {
        period?: number | null;
        validator_addrs?: string[] | null;
      };
    };
