/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      oracles: {
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      notes: {
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      current: {
        name: string;
        variable?: string | null;
      };
    }
  | {
      value: {
        name: string;
        variable: string;
      };
    }
  | {
      history: {
        limit?: number | null;
        name: string;
        start_after?: number | null;
        variable?: string | null;
      };
    }
  | {
      ownership: {};
    };
