/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {};
    }
  | {
      state: {};
    }
  | {
      validators: {};
    }
  | {
      action: {
        id: number;
      };
    }
  | {
      actions: {
        direction?: Direction | null;
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      user_actions: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
      };
    }
  | {
      balances: {
        assets?: AssetInfoBaseFor_String[] | null;
      };
    }
  | {
      oracle_prices: {
        assets?: AssetInfoBaseFor_String[] | null;
      };
    };
export type Direction = "asc" | "desc";
/**
 * Represents the type of an fungible asset.
 *
 * Each **asset info** instance can be one of three variants:
 *
 * - Native SDK coins. To create an **asset info** instance of this type, provide the denomination. - CW20 tokens. To create an **asset info** instance of this type, provide the contract address.
 */
export type AssetInfoBaseFor_String =
  | {
      native: string;
    }
  | {
      cw20: string;
    };
