/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes custom hooks for the CW20.
 */
export type Cw20HookMsg =
  | {
      bond: {
        staker_addr?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      unbond: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    };
