/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes query messages available in the contract.
 */
export type QueryMsg =
  | {
      config: {};
    }
  | {
      user_info: {
        addr: string;
      };
    }
  | {
      state: {
        addr?: string | null;
      };
    };
