/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | "active_channel"
  | "pair"
  | {
      remote_address: {
        local_address: string;
      };
    }
  | "block_max_gas";
