/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Nullable_Pair = Pair | null;

/**
 * This contract's voice. There is one voice per note, and many notes per voice.
 */
export interface Pair {
  connection_id: string;
  remote_port: string;
}
