/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {};
    }
  | {
      pool_info: {
        lp_token: string;
      };
    }
  | {
      user_info: {
        lp_token: string;
        user: string;
      };
    }
  | {
      reward_info: {
        token: string;
      };
    }
  | {
      pending_token: {
        lp_token: string;
        user: string;
      };
    }
  | {
      deposit: {
        lp_token: string;
        user: string;
      };
    }
  | {
      staking_state: {};
    }
  | {
      staker_info: {
        user: string;
      };
    };
