/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NftInfoResponseFor_Metadata {
  /**
   * You can add any custom metadata here when you extend cw721-base
   */
  extension: Metadata;
  /**
   * Universal resource identifier for this NFT Should point to a JSON file that conforms to the ERC721 Metadata JSON Schema
   */
  token_uri?: string | null;
}
export interface Metadata {
  attributes?: Trait[] | null;
  description?: string | null;
  image?: string | null;
  name?: string | null;
}
export interface Trait {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
