/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This enum describes available Token types. ## Examples ``` # use cosmwasm_std::Addr; # use astroport::asset::AssetInfo::{NativeToken, Token}; Token { contract_addr: Addr::unchecked("stake...") }; NativeToken { denom: String::from("uluna") }; ```
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: Addr;
      };
    }
  | {
      native_token: {
        denom: string;
      };
    };
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

/**
 * This structure describes the parameters for creating a contract.
 */
export interface InstantiateMsg {
  /**
   * Information about the amp[LP] Token for pool shares.
   */
  amp_lp?: TokenInit | null;
  /**
   * Information about the amp[LP] Token for pool shares.
   */
  amp_lp_denom?: string | null;
  /**
   * the base reward token contract address
   */
  base_reward_token: AssetInfo;
  /**
   * The compound proxy contract address
   */
  compound_proxy: string;
  /**
   * The controller address to execute compound
   */
  controller: string;
  deposit_profit_delay_s: number;
  /**
   * The performance fee
   */
  fee: Decimal;
  /**
   * The fee collector contract address
   */
  fee_collector: string;
  /**
   * The LP token contract address
   */
  liquidity_token: string;
  /**
   * The owner address
   */
  owner: string;
  /**
   * The LP staking generator contract address
   */
  staking_contract: string;
}
export interface TokenInit {
  /**
   * Code Id of the amp[LP] token
   */
  cw20_code_id: number;
  /**
   * Number of decimals of the liquid staking token
   */
  decimals: number;
  /**
   * Name of the liquid staking token
   */
  name: string;
  /**
   * Symbol of the liquid staking token
   */
  symbol: string;
}
