/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LiquidStakingType = "eris" | "stader" | "steak";
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

export interface ConfigResponse {
  /**
   * Hub contract
   */
  hub_contract: string;
  /**
   * defines how to interact with the hub_contract for reading the exchange_rate
   */
  interface: LiquidStakingType;
  /**
   * Address of the lp token
   */
  lp_token: string;
  /**
   * Pending ownership transfer, awaiting acceptance by the new owner
   */
  new_owner?: string | null;
  /**
   * Account who can call certain privileged functions
   */
  owner: string;
  /**
   * Address of the stake token
   */
  stake_token: string;
  /**
   * Address where extracted yield should be deposited
   */
  yield_extract_addr: string;
  /**
   * Percentage of yield that should be extracted (between 0 and 1)
   */
  yield_extract_p: Decimal;
  [k: string]: unknown;
}
