/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RouteTypeResponseItem =
  | {
      Path: {
        route: string[];
        router: string;
        router_type: RouterType;
        [k: string]: unknown;
      };
    }
  | {
      PairProxy: {
        asset_infos: string[];
        pair_contract: string;
        [k: string]: unknown;
      };
    };
export type RouterType = "astro_swap" | "terra_swap" | "token_swap";

export interface RouteResponseItem {
  key: [string, string];
  route_type: RouteTypeResponseItem;
  [k: string]: unknown;
}
