/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      bond: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      donate: {
        [k: string]: unknown;
      };
    }
  | {
      withdraw_unbonded: {
        receiver?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      add_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      remove_validator: {
        validator: string;
        [k: string]: unknown;
      };
    }
  | {
      transfer_ownership: {
        new_owner: string;
        [k: string]: unknown;
      };
    }
  | {
      drop_ownership_proposal: {
        [k: string]: unknown;
      };
    }
  | {
      accept_ownership: {
        [k: string]: unknown;
      };
    }
  | {
      harvest: {
        stages?: [Addr, AssetInfo][][] | null;
        [k: string]: unknown;
      };
    }
  | {
      tune_delegations: {
        [k: string]: unknown;
      };
    }
  | {
      rebalance: {
        min_redelegation?: Uint128 | null;
        [k: string]: unknown;
      };
    }
  | {
      reconcile: {
        [k: string]: unknown;
      };
    }
  | {
      submit_batch: {
        [k: string]: unknown;
      };
    }
  | {
      vote: {
        proposal_id: number;
        vote: VoteOption;
        [k: string]: unknown;
      };
    }
  | {
      vote_weighted: {
        proposal_id: number;
        votes: [Decimal, VoteOption][];
        [k: string]: unknown;
      };
    }
  | {
      callback: CallbackMsg;
    }
  | {
      update_config: {
        /**
         * Specifies wether donations are allowed.
         */
        allow_donations?: boolean | null;
        /**
         * Strategy how delegations should be handled
         */
        delegation_strategy?: DelegationStrategyFor_String | null;
        /**
         * Sets a new operator
         */
        operator?: string | null;
        /**
         * Contract address where fees are sent
         */
        protocol_fee_contract?: string | null;
        /**
         * Fees that are being applied during reinvest of staking rewards
         */
        protocol_reward_fee?: Decimal | null;
        /**
         * Sets the stages preset
         */
        stages_preset?: [Addr, AssetInfo][][] | null;
        /**
         * Update the vote_operator
         */
        vote_operator?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      claim: {
        claims: ClaimType[];
        [k: string]: unknown;
      };
    };
/**
 * A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.
 *
 * # Examples
 *
 * Use `from` to create instances of this and `u128` to get the value out:
 *
 * ``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);
 *
 * let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);
 *
 * let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```
 */
export type Uint128 = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>. See also <https://github.com/CosmWasm/cosmwasm/blob/main/docs/MESSAGE_TYPES.md>.
 */
export type Binary = string;
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;
/**
 * This enum describes available Token types. ## Examples ``` # use cosmwasm_std::Addr; # use astroport::asset::AssetInfo::{NativeToken, Token}; Token { contract_addr: Addr::unchecked("terra...") }; NativeToken { denom: String::from("uluna") }; ```
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: Addr;
        [k: string]: unknown;
      };
    }
  | {
      native_token: {
        denom: string;
        [k: string]: unknown;
      };
    };
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;
export type CallbackMsg =
  | {
      swap: {
        stage: [Addr, AssetInfo][];
        [k: string]: unknown;
      };
    }
  | {
      reinvest: {
        [k: string]: unknown;
      };
    }
  | {
      check_received_coin: {
        snapshot: Coin;
        snapshot_stake: Description;
        [k: string]: unknown;
      };
    };
export type DelegationStrategyFor_String =
  | "uniform"
  | {
      gauges: {
        /**
         * weight between amp and emp gauges between 0 and 1
         */
        amp_factor_bps: number;
        /**
         * gauges based on vAmp voting
         */
        amp_gauges: string;
        /**
         * gauges based on eris merit points
         */
        emp_gauges?: string | null;
        /**
         * max amount of delegation needed
         */
        max_delegation_bps: number;
        /**
         * min amount of delegation needed
         */
        min_delegation_bps: number;
        /**
         * count of validators that should receive delegations
         */
        validator_count: number;
        [k: string]: unknown;
      };
    };
export type ClaimType = {
  default: string;
};

/**
 * Cw20ReceiveMsg should be de/serialized under `Receive()` variant in a ExecuteMsg
 */
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
/**
 * This enum describes a Terra asset (native or CW20).
 */
export interface Description {
  /**
   * A token amount
   */
  amount: Uint128;
  /**
   * Information about an asset stored in a [`AssetInfo`] struct
   */
  info: AssetInfo;
  [k: string]: unknown;
}
