/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {};
    }
  | {
      state: {};
    }
  | {
      wanted_delegations: {};
    }
  | {
      simulate_wanted_delegations: {
        /**
         * by default uses the next period to look into the future.
         */
        period?: number | null;
      };
    }
  | {
      pending_batch: {};
    }
  | {
      previous_batch: number;
    }
  | {
      previous_batches: {
        limit?: number | null;
        start_after?: number | null;
      };
    }
  | {
      unbond_requests_by_batch: {
        id: number;
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      unbond_requests_by_user: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
      };
    }
  | {
      unbond_requests_by_user_details: {
        limit?: number | null;
        start_after?: number | null;
        user: string;
      };
    };
