/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      mint: {};
    }
  | {
      withdraw: {
        tokens?: string[] | null;
      };
    }
  | {
      refund: {
        burn: boolean;
        recipient: string;
        tokens?: string[] | null;
      };
    }
  | {
      update_data: {
        clear_whitelist?: boolean | null;
        set_available_nfts?: string[] | null;
        update_whitelist?: WhitelistEntry[] | null;
      };
    }
  | {
      update_config: {
        candy_type?: CandyType | null;
        mint_fee_recipient?: string | null;
        paused?: boolean | null;
      };
    }
  | {
      update_config_admin: {
        controller?: string | null;
        protocol_fee?: Decimal | null;
      };
    };
export type CandyType =
  | {
      pre_mint: {};
    }
  | {
      mint: {};
    };
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

export interface WhitelistEntry {
  address: string;
  phases: WhitelistPhaseEntry[];
}
export interface WhitelistPhaseEntry {
  amount: number;
  phase: number;
}
